# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Shoplyst CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET_KEY: ${{secrets.SECRET_KEY}}

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev -y
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
    - name: Test with pytest
      run: |
        pipenv run pytest
        
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Deploy Application
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "shoplyst"
        heroku_email: "me@gilsondev.in"
